version: 2
formats: all
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  image: latest

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
    - path: .